default_stages: [commit, push]
default_language_version:
  python: python3
minimum_pre_commit_version: '3.5.0'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace at end of line
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        name: ruff-lint
        args: [--fix]
      - id: ruff-format
        name: ruff-format