
version: '3.8'
services:
  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    volumes:
    - ./docs/apispecs/3rd-party-api:/etc/openapi
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/etc/openapi/openapi.yaml'
      OPENAPI_MOCK_USE_EXAMPLES: 'if_present'
    ports:
      - "9000:8080"
  # Fast-API service
  acmesports:
    container_name: acmesports
    image: acmesports
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18000:18000"
    depends_on:
      - openapi_mock